# https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-WebsitedeploymentserviceforGitrepositories

# TODO: use automatic Pelican building? https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-PelicanCMS

publish:
  whoami: asf-site

# https://allura.staged.apache.org/
# staging:
#  whoami: asf-staging
